version: '3'
services:
  quickbuy-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - mysql5.7-quickbuy

  mysql5.7-quickbuy:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:33060
    volumes:
      - quickbuydb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: numsey

volumes:
  quickbuydb:
